default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: dilkhush
  host: 127.0.0.1

development:
  <<: *default
  database: rails-neo4j-example_development

test:
  <<: *default
  database: rails-neo4j-example_test

production:
  <<: *default
  database: rails-neo4j-example_production
